### ISSUE TITLE
6.X-4 Centered symbols

### ISSUE THREAD

**Issue by rmalyankar** [IHO-S100WG/TSM8#10]
I think the language in S-98 Annex C ("center the symbol") is sufficient and works well enough where it is. 

> **C-8.2.4 Area fills**
> _The portrayal catalogue offers various ways to fill areas. They can be filled with an opaque colour; with a colour shown with some transparency; or with a pattern of symbols (fill pattern) or with a centred symbol. Fill patterns and centred symbols are introduced as a solution for the symbolization of areas in special situations. A fill pattern showing arrows does not have a certain position on the chart like the paper chart arrow symbol. It shows up as long as any part of the traffic separation lane can be seen on the screen. A centred symbol moves to the centre of the part of the area that remains in the display window. Fill patterns or centred area symbols may be used to symbolize the case when the entire display window lies within an area.
> The portrayal catalogue provides two options for area boundaries, referred to as “plain” and “symbolised”._
> 
> _Centred symbols must be used with symbolized boundaries to symbolize the case when the entire display window lies within an area._
> 
> _Area boundaries should not be visible on the edge of the display window when the display window is enclosed by an area. However, if the boundary is actually on the edge of the display window, it should be visible._

That said, if I were designing this de novo I would place the symbols as follows:
- where the area is clipped by a screen edge, within the area as near as possible to the middle of the screen edge;
- where the area is wholly inside a screen edge, within the area as near as possible to the intersection of the boundary and the perpendicular from the centroid to the screen edge;
- and, distributing coincident symbols to minimize obscuring symbols.

**Comment by DavidGrant-NIWC** [comment]
Recommend note this (no proposal required) in the 6.X-4 placeholder document.
