### ISSUE TITLE
6.8 Roles in feature catalogues

### ISSUE THREAD

**Issue by rmalyankar** [IHO-S100WG/TSM8#14]
Noting that there has been zero input or feedback on this proposal since TSM8 in March 2021, and noting that the [proposal](https://github.com/IHO-S100WG/TSM8/blob/main/6.8%20Roles%20in%20Feature%20Catalogues/TSM8_2021_6.8_S-100-MaintProp-Roles_in_Feature_Catalogues.pdf) allows product specifications to impose constraints on which bindings are actually encoded (which means that any product specification can restrict bindings in that data product to be in only one direction), it is recommended that this proposal be taken up by the S-100 working group and accepted as-is.

**Comment by DavidGrant-NIWC** [comment]
I agree with the proposal, but I think the following could be clarified:

> and noting that the proposal allows product specifications to impose constraints on which bindings are actually encoded

From the proposal:
> _Note that Product Specifications or data formats may impose constraints on whether bindings are actually encoded in either of the participating feature instances in datasets._

How? If this is indicated by the lack of a binding in the FC then that should be clearly spelled out. I'm also not sure how a data format could impose this constraint.

**Comment by rmalyankar** [comment]
There are different ways in which this could be done. Omitting the binding in the FC is only one of them. Doing it that way could actually get rather complex when it comes to creating a dataset. I suspect, but have not tried to prove, that there may be circumstances where it actually makes it impossible to create a valid dataset (e.g., if the format also prohibits forward references).

The data format could impose a constraint by merely prohibiting forward references regardless of what the FC contains. Better to leave "how" to a product specification that actually needs to restrict the encoding of bindings.

**Comment by HolgerBothien** [comment]
In general I agree with the proposal.

The actual encoding is specified by the encoding sections of S-100 and not by a product spec. Otherwise it would be difficult to implement. We implement the main standard and not specific product specifications. So I would remove the sentence:

> Note that Product Specifications or data formats may impose constraints on whether bindings are actually encoded in either of the participating feature instances in datasets.

Or at least remove Product Specifications from the sentence.

Another point: Does the three types of association for Information Bindings makes sense? OR is it always "association" there?

**Comment by rmalyankar** [comment]
I have removed the mention of "Product Specifications" from the final sentences of 5-4.2.5.2 and 5-4.2.5.3 and will post an updated version shortly.

Information associations can link information types and some product may use aggregation or compositon to satisfy a domain-specific requirement. So S-100 should not prohibit aggregation and composition for information bindings.
