### ISSUE TITLE
6.X-5 Metadata temporal attributes - closure attribute

### ISSUE THREAD

**Issue by rmalyankar** [IHO-S100WG/TSM8#16]
During discussions on 14 October I mentioned adding a closure attribute, but having drafted a revised proposal, I realized that the case for the closure attribute in discovery metadata is weak, given that the bounds of a dataset's validity can be encoded down to the second and indefinite validity can be represented by omitting the end time. Can anyone come up with stronger use cases for using closure in discovery metadata temporal extent?

See [version 2 of the proposal](https://github.com/IHO-S100WG/TSM8/tree/main/6.X-5%20Metadata%20temporal%20attributes), posted  to GitHub on 18 October.

**Comment by gseroka** [comment]
Agree that closure may not be needed. I don't immediately foresee a use case for the example provided in the proposal below. Rather, EXAMPLE 1 should be sufficient in satisfying most or all of the S-104 use cases that I can think of.

EXAMPLE 2: An S-104 (Water Level Information for Surface Navigation) predictions dataset has the following data for temporalExtent:
<temporalExtent>
    <timeInstantBegin>2021-07-03T12:00:00Z</timeInstantBegin>
    <timeInstantEnd>2021-07-10T24:00:00Z</timeInstantEnd>
    <closure> geLtInterval</closure>
</temporalExtent>

**Comment by rmalyankar** [comment]
Will remove _closure_ from metadata, one way or another - either by adding a constraint prohibiting the use of _closure_ in dataset discovery metadata, or removing it from the type definition.
